name: Manga Tracker Automation

on:
  schedule:
    - cron: '*/20 * * * *'  # Every 30 minutes
  workflow_dispatch:  # Allows for manual triggering of the workflow

jobs:
  track_manga:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install the required packages

    - name: Run Manga Tracker
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}  # Use the secret
        CHAT_ID: ${{ secrets.CHAT_ID }}                # Use the secret
      run: |
        python demon5.py  # Replace with the name of your Python file

    - name: Commit and Push Changes
      run: |
        git config --local user.email "ekveda24@gmail.com"  # Your email
        git config --local user.name "Kashishveda"  # Your name
        git add manga_chapters.json
        git commit -m "Update manga chapters" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/Kashishveda/manga.git HEAD:master
